import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "How it works · WSB Pulse",
  description: "How WSB Pulse collects tickers, scores sentiment, and rates stocks with AI.",
};

export default function HowItWorks() {
  return (
    <article className="max-w-2xl space-y-4 text-sm leading-relaxed text-neutral-300">
      <h1 className="text-2xl font-semibold tracking-tight text-neutral-100">How it works</h1>
      <p>WSB Pulse watches r/WallStreetBets for stock tickers, then enriches and rates each one daily.</p>
      <ol className="list-decimal space-y-2 pl-5">
        <li><strong>Collect</strong> — posts mentioning tickers are pulled from r/WallStreetBets and tagged with a sentiment (positive / neutral / negative).</li>
        <li><strong>Research</strong> — each ticker gets a daily market snapshot from Finnhub (price, moves, fundamentals, news).</li>
        <li><strong>Rate</strong> — Claude reviews the chatter and research and assigns a <strong>Buy / Hold / Sell</strong> with a <strong>confidence</strong> score (0–100).</li>
      </ol>
      <p>The dashboard ranks tickers by Claude&apos;s confidence in its latest rating. &ldquo;Top movers&rdquo; highlights recent rating changes and spikes in WSB chatter. Data covers a rolling 90-day window.</p>
      <p className="text-neutral-500">Ratings are generated by an AI model for informational purposes only and are <strong>not financial advice</strong>.</p>
    </article>
  );
}
